excluded:
  - .build
  - Pods
  - DerivedData

disabled_rules:
  - trailing_whitespace
  - line_length

opt_in_rules:
  - empty_count
  - empty_string
  - force_unwrapping
  - missing_docs
  - closure_spacing
  - unneeded_parentheses_in_closure_argument

identifier_name:
  min_length: 2
  max_length: 40
  excluded:
    - id
    - URL
    - url
    - aws
    - s3

type_name:
  min_length: 3
  max_length: 40
  excluded:
    - S3

function_parameter_count:
  warning: 6
  error: 8

file_length:
  warning: 500
  error: 1000

cyclomatic_complexity:
  warning: 15
  error: 25

reporter: "xcode" 