excluded:
  - .build
  - Pods
  - DerivedData

disabled_rules:
  - trailing_whitespace
  - line_length
  - type_name
  - type_body_length
  - file_length
  - function_body_length

opt_in_rules:
  - empty_count
  - empty_string
  - force_unwrapping
  - missing_docs
  - closure_spacing
  - unneeded_parentheses_in_closure_argument

identifier_name:
  min_length: 2
  max_length: 40
  excluded:
    - id
    - URL
    - url
    - aws
    - s3

function_parameter_count:
  warning: 6
  error: 8

cyclomatic_complexity:
  warning: 15
  error: 25

reporter: "github-actions-logging" 